name: "Terraform Steps"
description: "Run Terraform plan from PRs and Terraform plan/apply from `main`"
inputs:
  client-id:
    description: "The service principal Client ID to use"
    required: true
  client-secret:
    description: "The service principal Client Secret to use. Please load it from a GitHub secret."
    required: true
  default-subscription-id:
    description: "The default Subscription ID to use. The service principal must have access."
    required: true
  tenant-id:
    description: "The Azure Active Directory Tenant ID to use."
    required: true
  working-directory:
    description: "The directory where the Terraform configuration is located."
    required: true
    default: .
  plan-title:
    description: "The title of the comment that GitHub will add after a `terraform plan`."
    required: true
  terraform-version:
    description: "The Terraform version to use"
    required: true
    default: "1.1.9"
  GITHUB_TOKEN:
    description: "The secrets.GITHUB_TOKEN so that the action can create a comment on the PR"
    required: true

branding:
  icon: "coffee"

runs:
  using: "composite"

  steps:
    # On push to main, build or change infrastructure according to Terraform configuration files
    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -input=false tf.plan
      env:
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_CLIENT_SECRET: ${{ inputs.client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.default-subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
